### ISSUE TITLE
cannot download the source code for sambvca21.exe

### ISSUE THREAD

**Issue by yajunzhao123** [JacksonBurns/py2sambvca#37]
Hi,

I'm a user of your web app. https://www.aocdweb.com/OMtools/sambvca2.1/index.html
It seems that there are some issues and shows an error message: `Internal error: can't open file input file.`

Therefore I tried to use the python package here.
But I cannot open the website writen in README to download the source code for sambvca21.exe,
and I encounter the error `RuntimeError: sambvca executable not found at provided path (sambvca21.exe)`.

Is there any solution for this? 
Thanks for your help.

**Comment by JacksonBurns** [comment]
Hi @yajunzhao123 that web app is actually run by the original authors of the sambvca program, not me. Any problems with the website should be sent to that team - you can find their contact info here: https://www.aocdweb.com/OMtools/sambvca2.1/info/info.html

Thanks for letting me know about the broken link. The link to the website has changed, you should now be able to download the source code from here: https://www.aocdweb.com/OMtools/sambvca2.1/download/download.html now. I will update the README.

The error that is raised by `py2sambvca` is because the executable file is missing. You will have to download the source code at the provided link, compile it (as mentioned in the README here), and then either (1) put the compiled executable (named `sambvca21.exe` in the same directory as your `py2sambvca` script or simply (2) provide the path to the executable in your call to `py2sambvca`, i.e. ` path_to_sambvcax=/path/to/executable`. The file extension might be different based on your operating system.
